import "./App.css";

function App() {
  return (
    <div className="container">
      <h4 className="headerTxt">privacy and policy of Almuqtadir Gold App</h4>
      <p className="subheadertxt">
        This Application collects some Personal Data from its Users.
      </p>
      <p>
        This document can be printed for reference by using the print command in
        the settings of any browser.
      </p>
      <h5>Owner and Data Controller</h5>
      <p className="address">IQRAHUB IT SOLUTIONS LLP</p>
      <p className="address">T.C 28/259, TSGRA 73</p>
      <p className="address">Back side of Cordial Shroffs Apartment</p>
      <p className="address">Thycuad,Thiruvanandapuram</p>
      <p className="address">Kerala,695014</p>
      <p>
        Owner contact email:{" "}
        <a href="mailto:support@iqrahub.com">support@iqrahub.com</a>
      </p>
      <hr />
      <h4 className="headerTxt">privacy policy</h4>
      <p>Updated at 2022-05-27</p>
      <div>
        <p>
          Al Muqtadir Jewellery Group (“we,” “our,” or “us”) is committed to
          protecting your privacy. This Privacy Policy explains how your
          personal information is collected, used, and disclosed by Al Muqtadir
          Jewellery Group through our mobile application.
        </p>
        <p>
          This Privacy Policy applies to our mobile app and its associated
          services. By accessing or using our mobile app, you signify that you
          have read, understood, and agree to our collection, storage, use, and
          disclosure of your personal information as described in this Privacy
          Policy. This Privacy Policy was created with Termify.
        </p>
      </div>
      <div>
        <h5>Definitions and Key Terms</h5>
      </div>
      <div>
        <p>
          To help explain things as clearly as possible in this Privacy Policy,
          every time any of these terms are referenced, are strictly defined as:
        </p>
        <p>
          <span style={{ fontWeight: "bold" }}>Cookies:</span> A small amount of
          data generated by the app and saved by your device
        </p>
        <p>
          <span style={{ fontWeight: "bold" }}>Company:</span> Refers to Al Muqtadir Jewellery Group, the entity responsible for your
          information under this Privacy Policy.
        </p>
        <p>
          <span style={{ fontWeight: "bold" }}>Country:</span> The location where Al Muqtadir Jewellery Group is based, in this case,
          India.
        </p>
        <p>
          <span style={{ fontWeight: "bold" }}>Customer:</span> Refers to the company, organization, or person using the Al Muqtadir
          Jewellery Group mobile app.
        </p>
        <p>
          <span style={{ fontWeight: "bold" }}>Device:</span> Any internet-connected device such as a phone or tablet that can be
          used to access the app.
        </p>
        <p>
          <span style={{ fontWeight: "bold" }}> IP address:</span> A unique identifier assigned to each device connected to the Internet.
        </p>
        <p>
          <span style={{ fontWeight: "bold" }}>Personnel:</span> Individuals employed by or under contract with Al Muqtadir Jewellery
          Group.
        </p>
        <p>
          <span style={{ fontWeight: "bold" }}>Personal Data:</span> Information that allows for the identification of a natural person.
        
        </p>
        <p>
          <span style={{ fontWeight: "bold" }}>Service:</span> The services provided by Al Muqtadir Jewellery Group through its
          mobile app.
        </p>
        <p>
          <span style={{ fontWeight: "bold" }}>Third-party service:</span> Advertisers, sponsors, and partners providing content or services
          within the app.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>What Information Do We Collect?</h5>
      </div>
      <div>
        <p style={{marginTop:-15}}>
        We collect information from you when you use our mobile app, register
          an account, place an order, subscribe to our newsletter, respond to a
          survey, or fill out a form. The collected information may include:
        </p>
        <p>&#x2022; Name/Username</p>
        <p>&#x2022; Phone Numbers</p>
        <p>&#x2022; Email Addresses</p>
        <p>&#x2022; Mailing Addresses</p>
        <p>&#x2022; Job Titles</p>
        <p>&#x2022; Billing Addresses</p>
        <p>&#x2022; Debit/Credit Card Numbers</p>
        <p>&#x2022; Password</p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>When Does Al Muqtadir Jewellery Group Use End-User Information from
          Third Parties?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Al Muqtadir Jewellery Group may collect end-user data necessary to
          provide its services. Users may voluntarily provide information
          through social media integrations. If provided, publicly available
          information from indicated social media accounts may also be
          collected.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>When Does Al Muqtadir Jewellery Group Use Customer Information from
          Third Parties?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Customer information may be received from third parties when users
          contact us. For instance, when expressing interest in becoming an Al
          Muqtadir Jewellery Group customer, information from third-party fraud
          detection services may be obtained.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Do We Share the Information We Collect with Third Parties?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      We may share collected information, both personal and non-personal,
          with third parties such as advertisers, sponsors, and service
          providers. Trusted third-party service providers may be engaged to
          perform various functions necessary for the app's operation, including
          hosting, database management, email services, and order fulfillment.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Where and When Is Information Collected from Customers and End Users?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Personal information is collected when submitted by users. Information
          may also be received from third parties, as described above.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>How Do We Use the Information We Collect?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Collected information is used for various purposes, including
          personalizing user experiences, improving the app, enhancing customer
          service, processing transactions, and administering contests or
          surveys.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>How Do We Use Your Email Address?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      By submitting your email address, you agree to receive emails from us.
          You can opt-out at any time. We use email addresses for customer
          communication, order updates, and, with your consent, for targeted
          advertising on platforms like Facebook.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}> How Long Do We Keep Your Information?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      We retain your information for as long as necessary to provide
          services and fulfill the purposes outlined in this policy. Once no
          longer needed, we either remove or depersonalize the data.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>  How Do We Protect Your Information?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      We implement security measures, including encryption and secure
          servers, to protect your personal information. While we take
          reasonable efforts, absolute security cannot be guaranteed
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>  Could My Information Be Transferred to Other Countries?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Information collected may be transferred and hosted worldwide. By
          using the app, you consent to trans-border transfer and hosting of
          your information.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>  Is the Information Collected through the Al Muqtadir Jewellery Group
          Service Secure?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Reasonable measures are taken to protect information, but absolute
          security cannot be guaranteed. Users accept that intentional
          misconduct is the standard for compliance with duties to protect
          personal information.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>  Can I Update or Correct My Information?</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Users may update or correct personal information by contacting us.
          Verification of identity may be required for security. Users are
          responsible for maintaining password secrecy.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Rights of Data Subjects - Data Access, Portability, and Deletion</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      We assist users in exercising their data subject rights under GDPR.
          Personal data is stored securely and is accessible by users for
          updates or deletion.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Sale of Business</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Information may be transferred to a third party in the event of a
          business sale, merger, or reorganization.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Affiliates</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Information may be disclosed to corporate affiliates, with treatment
          consistent with this Privacy Policy.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Governing Law</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      This Privacy Policy is governed by Indian law. Users agree to the
          exclusive jurisdiction of Indian courts.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Your Consent</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      By using the Al Muqtadir Jewellery Group mobile app, you consent to
          this Privacy Policy.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Links to Other Websites</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      This Privacy Policy applies only to the app. External links are not
          under our control, and users should review the privacy policies of
          linked websites.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Cookies</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      The app uses cookies for performance and functionality. Disabling
          cookies may affect app functionality.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Remarketing Services</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Remarketing services may be used for advertising effectiveness. Users
          are subject to the privacy policies of these services.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Payment Details</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Credit card or payment details are stored securely.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Kids Privacy</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      We collect information from users under 13 for service improvement.
          Parents can contact us to address unauthorized data collection.
        </p>
      </div>
      <div>
        <h5 style={{marginTop:30}}>Changes To Our Privacy Policy</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Users will be notified of changes, and continued use implies
          acceptance.
        </p>
        </div>
        <div>
        <h5 style={{marginTop:30}}>Third-Party Services</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      We are not responsible for third-party services. Users access and use
          them at their own risk.
        </p>
        </div>
        <div>
        <h5 style={{marginTop:30}}>Facebook Pixel</h5>
      </div>
      <div>
      <p style={{marginTop:-15}}>
      Facebook pixel is an analytics tool that allows you to measure the
          effectiveness of your advertising by understanding the actions people
          take on your website. You can use the pixel to: Make sure your ads are
          shown to the right people. Facebook pixel may collect information from
          your device when you use the service. Facebook pixel collects
          information that is held in accordance with its Privacy Policy.
        </p>
        </div>
        <div>
        <h4 style={{marginTop:30,textAlign:'center'}}>Tracking Technologies</h4>
      </div>
      <div>
      <h5 style={{marginTop:30}}>Google Maps API</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      Google Maps API is a robust tool that can be used to create a custom
          map, a searchable map, check-in functions, display live data synching
          with location, plan routes, or create a mashup just to name a
          few.Google Maps API may collect information from You and from Your
          Device for security purposes.Google Maps API collects information that
          is held in accordance with its Privacy Policy.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30}}>Cookies</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      GGoogle Maps API is a robust tool that can be used to create a custom
          map, a searchable map, check-in functions, display live data synching
          with location, plan routes, or create a mashup just to name a
          few.Google Maps API may collect information from You and from Your
          Device for security purposes.Google Maps API collects information that
          is held in accordance with its Privacy Policy.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30}}>Local Storage</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      Local Storage sometimes known as DOM storage, provides web apps with
          methods and protocols for storing client-side data. Web storage
          supports persistent data storage, similar to cookies but with a
          greatly enhanced capacity and no information stored in the HTTP
          request header.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30}}>Sessions</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      uses “Sessions” to identify the areas of our website that you have
          visited. A Session is a small piece of data stored on your computer or
          mobile device by your web browser.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30,textAlign:'center'}}>Information about General Data Protection Regulation (GDPR)</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      We may be collecting and using information from you if you are from
          the European Economic Area (EEA), and in this section of our Privacy
          Policy we are going to explain exactly how and why is this data
          collected, and how we maintain this data under protection from being
          replicated or used in the wrong way.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30}}>What is GDPR?</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      GDPR is an EU-wide privacy and data protection law that regulates how
          EU residents’ data is protected by companies and enhances the control
          the EU residents have, over their personal data.
        </p>
        <p style={{marginTop:-5}}>
             The GDPR is relevant to any globally operating company and not just
          the EU-based businesses and EU residents. Our customers’ data is
          important irrespective of where they are located, which is why we have
          implemented GDPR controls as our baseline standard for all our
          operations worldwide.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30}}>What is personal data?</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      Any data that relates to an identifiable or identified individual.
          GDPR covers a broad spectrum of information that could be used on its
          own, or in combination with other pieces of information, to identify a
          person. Personal data extends beyond a person’s name or email address.
          Some examples include financial information, political opinions,
          genetic data, biometric data, IP addresses, physical address, sexual
          orientation, and ethnicity.
        </p>
      <p style={{marginTop:-1}}>
      The Data Protection Principles include requirements such as:
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Personal data collected must be processed in a fair, legal,
          and transparent way and should only be used in a way that a person
          would reasonably expect.
        </p>
      <p style={{marginTop:-10}}>
      &#x2022; Personal data should only be collected to fulfil a specific
          purpose and it should only be used for that purpose. Organizations
          must specify why they need the personal data when they collect it.
        </p>
      <p style={{marginTop:-10}}>
      &#x2022; Personal data should be held no longer than necessary to
          fulfil its purpose.
        </p>
      <p style={{marginTop:-10}}>
      &#x2022; People covered by the GDPR have the right to access their own
          personal data. They can also request a copy of their data, and that
          their data be updated, deleted, restricted, or moved to another
          organization.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30}}>Why is GDPR important?</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      GDPR adds some new requirements regarding how companies should protect
          individuals’ personal data that they collect and process. It also
          raises the stakes for compliance by increasing enforcement and
          imposing greater fines for breach. Beyond these facts it’s simply the
          right thing to do. At Al Muqtadir Jewellery Group we strongly believe
          that your data privacy is very important and we already have solid
          security and privacy practices in place that go beyond the
          requirements of this new regulation.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30}}> Individual Data Subject’s Rights – Data Access, Portability and
          Deletion</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      We are committed to helping our customers meet the data subject rights
          requirements of GDPR. Al Muqtadir Jewellery Group processes or stores
          all personal data in fully vetted, DPA compliant vendors. We do store
          all conversation and personal data for up to 6 years unless your
          account is deleted. In which case, we dispose of all data in
          accordance with our Terms of Service and Privacy Policy, but we will
          not hold it longer than 60 days.
        </p>
      <p style={{marginTop:-15}}>
      We are aware that if you are working with EU customers, you need to be
          able to provide them with the ability to access, update, retrieve and
          remove personal data. We got you! We’ve been set up as self service
          from the start and have always given you access to your data and your
          customers data. Our customer support team is here for you to answer
          any questions you might have about working with the API.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30}}> California Residents</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      The California Consumer Privacy Act (CCPA) requires us to disclose
          categories of Personal Information we collect and how we use it, the
          categories of sources from whom we collect Personal Information, and
          the third parties with whom we share it, which we have explained
          above.
        </p>
      <p style={{marginTop:-1}}>
      We are also required to communicate information about rights
          California residents have under California law. You may exercise the
          following rights:
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Right to Know and Access. You may submit a verifiable request
          for information regarding the: (1) categories of Personal Information
          we collect, use, or share; (2) purposes for which categories of
          Personal Information are collected or used by us; (3) categories of
          sources from which we collect Personal Information; and (4) specific
          pieces of Personal Information we have collected about you.
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Right to Equal Service. We will not discriminate against you
          if you exercise your privacy rights.
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Right to Delete. You may submit a verifiable request to close
          your account and we will delete Personal Information about you that we
          have collected.
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Request that a business that sells a consumer’s personal
          data, not sell the consumer’s personal data.
        </p>
      <p style={{marginTop:-1}}>
      If you make a request, we have one month to respond to you. If you
          would like to exercise any of these rights, please contact us.
        </p>
      <p style={{marginTop:-1}}>
      We do not sell the Personal Information of our users.
        </p>
      <p style={{marginTop:-1}}>
      For more information about these rights, please contact us.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30}}> California Online Privacy Protection Act (CalOPPA)</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      CalOPPA requires us to disclose categories of Personal Information we
          collect and how we use it, the categories of sources from whom we
          collect Personal Information, and the third parties with whom we share
          it, which we have explained above.
        </p>
      <p style={{marginTop:-1}}>
      CalOPPA users have the following rights:
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Right to Know and Access. You may submit a verifiable request
          for information regarding the: (1) categories of Personal Information
          we collect, use, or share; (2) purposes for which categories of
          Personal Information are collected or used by us; (3) categories of
          sources from which we collect Personal Information; and (4) specific
          pieces of Personal Information we have collected about you.
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Right to Equal Service. We will not discriminate against you
          if you exercise your privacy rights.
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Right to Delete. You may submit a verifiable request to close
          your account and we will delete Personal Information about you that we
          have collected.
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Right to request that a business that sells a consumer’s
          personal data, not sell the consumer’s personal data.
        </p>
      <p style={{marginTop:-1}}>
      If you make a request, we have one month to respond to you. If you
          would like to exercise any of these rights, please contact us.
        </p>
      <p style={{marginTop:-1}}>
      We do not sell the Personal Information of our users.
        </p>
      <p style={{marginTop:-1}}>
      For more information about these rights, please contact us.
        </p>
        </div>
        <div>
      <h5 style={{marginTop:30}}>Contact Us</h5>
        </div>
        <div>
      <p style={{marginTop:-15}}>
      Don’t hesitate to contact us if you have any questions.
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Via Phone Number: +919072222112
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Via this Link:<a href="https://AlMuqtadirJewelleryGroup.com/index.php/contact-us/">https://AlMuqtadirJewelleryGroup.com/index.php/contact-us/</a>
        </p>
      <p style={{marginTop:-1}}>
      &#x2022; Vis mail: T.C. 25/595-7, KOCHUVEETIL TOWER, Manorama Road,
          Thampanoor, Thiruvananthapuram, Kerala, 695001
        </p>
        </div>
    </div>
  );
}

export default App;
